# Generated by Django 2.2 on 2019-05-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectTab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DrugShopNet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameNet', models.CharField(max_length=20)),
                ('urlNet', models.CharField(max_length=127)),
                ('town', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MyCookie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopnet', models.CharField(max_length=20)),
                ('cookie', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=10)),
                ('link', models.CharField(max_length=127)),
            ],
        ),
    ]
