# Generated by Django 2.2 on 2019-05-01 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppConnectDb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mycookie',
            old_name='shopnet',
            new_name='nameNet',
        ),
    ]
