# Generated by Django 2.2 on 2019-05-01 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppConnectDb', '0002_auto_20190501_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycookie',
            name='nameNet',
        ),
    ]
