# Generated by Django 2.2 on 2019-05-04 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppConnectDb', '0003_remove_mycookie_namenet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConnectTab',
        ),
    ]
