# Generated by Django 2.2 on 2019-05-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppConnectDb', '0006_auto_20190506_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='link',
            field=models.URLField(max_length=127),
        ),
    ]
