# Generated by Django 2.2 on 2019-05-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppConnectDb', '0007_auto_20190512_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='link',
            field=models.CharField(max_length=127),
        ),
    ]
