# Generated by Django 2.2 on 2019-05-12 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppConnectDb', '0008_auto_20190512_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='price',
        ),
    ]
