# Generated by Django 2.2 on 2019-05-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppConnectDb', '0010_position_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='requ',
            field=models.IntegerField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
