# Generated by Django 2.2 on 2019-05-12 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppConnectDb', '0011_position_requ'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='requ',
        ),
    ]
