# Generated by Django 2.2 on 2019-05-12 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppConnectDb', '0012_remove_position_requ'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='requ',
            field=models.IntegerField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
