# Generated by Django 2.2 on 2019-05-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppConnectDb', '0013_position_requ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='requ',
            field=models.IntegerField(max_length=50),
        ),
    ]
