# Generated by Django 2.2 on 2019-05-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppConnectDb', '0014_auto_20190515_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='requestNumder',
            field=models.IntegerField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
