# Generated by Django 2.2 on 2019-05-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppConnectDb', '0017_drugshopnet_pathnet'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugshopnet',
            name='class_link',
            field=models.CharField(default=1, max_length=127),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drugshopnet',
            name='class_price',
            field=models.CharField(default=1, max_length=127),
            preserve_default=False,
        ),
    ]
