# Generated by Django 2.2 on 2019-06-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppConnectDb', '0018_auto_20190520_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='net',
            field=models.CharField(default=0, max_length=127),
            preserve_default=False,
        ),
    ]
