# Generated by Django 2.2 on 2019-06-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppConnectDb', '0020_remove_position_requ'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='counter',
            field=models.IntegerField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
