# Generated by Django 2.2 on 2019-06-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppConnectDb', '0021_position_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='product_tag',
            field=models.CharField(default=12, max_length=50),
            preserve_default=False,
        ),
    ]
