# Generated by Django 2.2 on 2019-06-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppConnectDb', '0024_drugshopnet_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugshopnet',
            name='price_tag',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
