# Generated by Django 2.2 on 2019-06-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppConnectDb', '0025_drugshopnet_price_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugshopnet',
            name='price_re',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
