# Generated by Django 2.2 on 2019-06-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppConnectDb', '0026_drugshopnet_price_re'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugshopnet',
            name='link_re',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drugshopnet',
            name='link_tag',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drugshopnet',
            name='product_re',
            field=models.CharField(default='d', max_length=50),
            preserve_default=False,
        ),
    ]
