# Generated by Django 2.2 on 2019-06-23 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppConnectDb', '0027_auto_20190623_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_tag', models.CharField(max_length=50)),
                ('class_link', models.CharField(max_length=127)),
                ('link_re', models.CharField(max_length=50)),
                ('drugShopNet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AppConnectDb.DrugShopNet')),
            ],
        ),
    ]
