# Generated by Django 2.2 on 2019-06-23 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppConnectDb', '0028_link'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Link',
            new_name='Pattern',
        ),
    ]
