# Generated by Django 2.2 on 2019-06-23 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppConnectDb', '0030_auto_20190623_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='counter',
        ),
        migrations.RemoveField(
            model_name='position',
            name='price',
        ),
        migrations.RemoveField(
            model_name='search',
            name='requestNumber',
        ),
    ]
