# Generated by Django 2.2 on 2019-06-23 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppConnectDb', '0031_auto_20190623_1812'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pattern',
        ),
    ]
