# Generated by Django 2.2 on 2019-06-23 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppConnectDb', '0032_delete_pattern'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_tag', models.CharField(max_length=50)),
                ('class_link', models.CharField(max_length=127)),
                ('link_re', models.CharField(max_length=50)),
                ('class_price', models.CharField(max_length=127)),
                ('price_tag', models.CharField(max_length=50)),
                ('price_re', models.CharField(max_length=50)),
                ('product_tag', models.CharField(max_length=50)),
                ('class_name', models.CharField(max_length=127)),
                ('product_re', models.CharField(max_length=50)),
                ('drugShopNet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AppConnectDb.DrugShopNet')),
            ],
        ),
    ]
