# Generated by Django 2.2 on 2019-06-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppConnectDb', '0035_auto_20190623_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycookie',
            name='idNet',
            field=models.IntegerField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='position',
            name='price',
            field=models.IntegerField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='search',
            name='requestNumber',
            field=models.IntegerField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
