# Generated by Django 2.2 on 2019-06-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppConnectDb', '0036_auto_20190623_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='counter',
            field=models.IntegerField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
