# Generated by Django 2.2 on 2019-06-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppConnectDb', '0037_position_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drugshopnet',
            name='class_link',
        ),
        migrations.RemoveField(
            model_name='drugshopnet',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='drugshopnet',
            name='class_price',
        ),
        migrations.RemoveField(
            model_name='drugshopnet',
            name='link_re',
        ),
        migrations.RemoveField(
            model_name='drugshopnet',
            name='link_tag',
        ),
        migrations.RemoveField(
            model_name='drugshopnet',
            name='price_re',
        ),
        migrations.RemoveField(
            model_name='drugshopnet',
            name='price_tag',
        ),
        migrations.RemoveField(
            model_name='drugshopnet',
            name='product_re',
        ),
        migrations.RemoveField(
            model_name='drugshopnet',
            name='product_tag',
        ),
        migrations.AddField(
            model_name='pattern',
            name='price_re_end',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='position',
            name='price',
            field=models.IntegerField(max_length=20),
        ),
    ]
