# Generated by Django 2.2 on 2019-06-26 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppConnectDb', '0038_auto_20190624_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern',
            name='product_re_end',
            field=models.CharField(default=1, max_length=127),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pattern',
            name='price_re',
            field=models.CharField(max_length=127),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='price_re_end',
            field=models.CharField(max_length=127),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='product_re',
            field=models.CharField(max_length=127),
        ),
    ]
